### ISSUE TITLE
\Zend\Filter\Boolean with TYPE_FALSE_STRING option set returns true for null or unset input

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-filter#31]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://github.com/zendframework/zendframework/issues/7116
User: @pdizz
Created On: 2015-01-09T22:52:02Z
Updated At: 2015-01-10T19:21:51Z
Body
    <?php require_once(**DIR**.'/vendor/autoload.php');

```
$inputFilter = new \Zend\InputFilter\InputFilter();
$input = new \Zend\InputFilter\Input('thing');
$filter = new \Zend\Filter\Boolean(\Zend\Filter\Boolean::TYPE_FALSE_STRING);

$input->getFilterChain()->attach($filter);
$inputFilter->add($input);

$inputFilter->setData([]);
var_dump($inputFilter->getValue('thing'));

$inputFilter->setData(['thing' => null]);
var_dump($inputFilter->getValue('thing'));
```

outputs

```
bool(true)
bool(true)
```

Boolean filter without any options set returns false

---
### Comment

User: @Martin-P
Created On: 2015-01-10T19:21:51Z
Updated At: 2015-01-10T19:21:51Z
Body
It looks like this is by design. See: https://github.com/zendframework/zf2/blob/67f098af070b29d5042e89e936604df3193d2212/tests/ZendTest/Filter/BooleanTest.php#L268

---

**Comment by webimpress** [comment]
@pdizz

Yes, this is by design for that type. You can see more in the documentation:
https://docs.zendframework.com/zend-filter/standard-filters/#changing-the-default-behavior
but just to summary - type `TYPE_FALSE_STRING` (`false`): 
> Converts a string equal to the word "false" (case insensitive) to boolean `FALSE`
and then:
> All other given values will return TRUE by default.

If you use different type (`TYPE_NULL`) you will get whatever you need.
You can also use conjunction of these two types: `TYPE_FALSE_STRING | TYPE_NULL`.
